- .idea/.gitignore
- .idea/and06-nibobnebob.iml
- .idea/modules.xml
- .idea/vcs.xml
- Aos/app/src/main/AndroidManifest.xml
- Aos/app/src/main/java/com/avengers/nibobnebob/app/App.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/config/AccessTokenInterceptor.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
- Aos/app/src/main/res/layout/activity_main.xml
- Aos/app/src/main/res/values/colors.xml
- Hilt NetworkModule 구현
- Hilt ApiModule, RepositoryModule 세팅
- BaseFragment / BaseActivity 구현
- color resource 정의
- AccessTokenInterceptor, BearerInterceptor 세팅
> [etc/aos] 프로젝트 세팅

- be/.eslintrc.js
- be/.gitignore
- be/.prettierrc
- be/README.md
- be/nest-cli.json
- be/package-lock.json
- be/package.json
- be/src/app.controller.spec.ts
- be/src/app.controller.ts
- be/src/app.module.ts
- be/src/app.service.ts
- be/src/main.ts
- be/test/app.e2e-spec.ts
- be/test/jest-e2e.json
- be/tsconfig.build.json
- be/tsconfig.json
> [etc/be] 백엔드 초기세팅 #8

- be/.eslintrc.js
- be/.gitignore
- be/.prettierrc
- be/README.md
- be/nest-cli.json
- be/package-lock.json
- be/package.json
- be/src/app.controller.spec.ts
- be/src/app.controller.ts
- be/src/app.module.ts
- be/src/app.service.ts
- be/src/main.ts
- be/test/app.e2e-spec.ts
- be/test/jest-e2e.json
- be/tsconfig.build.json
- be/tsconfig.json
nest 설치 및 초기 세팅
nest swagger 설치
> 백엔드 초기 세팅 완료

- Aos/app/src/main/AndroidManifest.xml
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- 인트로 액티비티 메니페스트 추가
- BaseFragment 수정
Related to issue https://github.com/boostcampwm2023/and06-nibobnebob/issues/6
> [Login/aos] 인트로 협업 준비 #6

- Aos/.idea/misc.xml
- Aos/app/src/main/AndroidManifest.xml
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/DatePicker.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Validation.kt
- Aos/app/src/main/res/color/selector_next_btn_text.xml
- Aos/app/src/main/res/color/selector_nick_check_text.xml
- Aos/app/src/main/res/drawable/ic_back.xml
- Aos/app/src/main/res/drawable/ic_calendar.xml
- Aos/app/src/main/res/drawable/rect_dark1fill_nostroke_8radius.xml
- Aos/app/src/main/res/drawable/rect_primarylight3fill_nostroke_8radius.xml
- Aos/app/src/main/res/drawable/selector_next_btn.xml
- Aos/app/src/main/res/layout/activity_intro.xml
- Aos/app/src/main/res/layout/fragment_detail_signup.xml
- Aos/app/src/main/res/layout/fragment_login.xml
- Aos/app/src/main/res/navigation/intro_nav_graph.xml
- Aos/app/src/main/res/values-night/themes.xml
- Aos/app/src/main/res/values/colors.xml
- Aos/app/src/main/res/values/strings.xml
- Aos/app/src/main/res/values/text_style.xml
[상세 회원가입 구현(API 연결 전)](https://github.com/boostcampwm2023/and06-nibobnebob/pull/27)
> 상세 회원가입 구현 (API 연결 전)

- Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ConnectivityManagerModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/DetailSignupResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivityViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/mapper/UiSignupDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/model/UiSignupData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/my_list/MyRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wish_list/WishRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
- Aos/app/src/main/res/navigation/intro_nav_graph.xml
- NetworkManager 앱 전역 로직 구현 
- data layer package 생성
- presentation layer mapper 함수 예시 구현
- Login -> Signup 화면 이동 구현
Related to issue #3 
Related to issue #4 
Related to issue #6
> [Setting/aos] 안드로이드 추가세팅

- Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ConnectivityManagerModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/DetailSignupRequest.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/DetailSignupResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivityViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/mapper/UiSignupDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/model/UiSignupData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/my_list/MyRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wish_list/WishRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
- Aos/app/src/main/res/navigation/intro_nav_graph.xml
[안드로이드 추가 세팅](https://github.com/boostcampwm2023/and06-nibobnebob/pull/45)
> 안드로이드 추가 세팅

- be/src/baseresponse.ts
- be/src/error.filter.ts
- be/src/main.ts
- be/src/response.interceptor.ts
- be/src/user/dto/userInfo.dto.ts
- be/src/user/entities/user.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
baseResponse 설정 및 intercepter 구현
> baseResponse 설정

- be/src/auth/auth.module.ts
- be/src/auth/auth.service.ts
- be/src/main.ts
- be/src/user/dto/userInfo.dto.ts
- be/src/user/entities/user.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.decorator.ts
- be/src/user/user.module.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> 마이페이지 api 처리 기능 구현

- be/src/auth/strategy/jwt.strategy.ts
- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
마이 메인페이지 api 엔드포인트, 타 유저 메인페이지 api 엔드포인트 분리
Related to iusse : #18
> [Mypage/be] 마이 메인페이지 api 엔드포인트, 타 유저 메인페이지 api 엔드포인트 분리

- be/src/auth/auth.service.ts
- payload 수정
Related to Issue #6
> [Login/be] payload 수정

- be/src/auth/auth.controller.ts
- be/src/auth/auth.service.ts
- be/src/auth/dto/refreshToken.dto.ts
-  accesstoken 만료 시 동작 구현
Relate to Issue #35
> [Global/be] accessToken 만료 시 동작 구현

- be/package-lock.json
- be/package.json
- be/src/user/entities/user.entity.ts
- be/src/user/user.service.ts
- be/src/utils/encryption.utils.ts
> 회원가입 정보 암호화

- Aos/.idea/deploymentTargetDropDown.xml
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurant_add/AddMyRestaurantFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/global/restaurant_detail/RestaurantDetailFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/restaurant_search/RestaurantSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/BottomSheetManager.kt
- Aos/app/src/main/res/drawable/rect_primary1_nostroke_top_radius20.xml
- Aos/app/src/main/res/drawable/rect_primary3_nostroke_30radius.xml
- Aos/app/src/main/res/drawable/rect_primary3fill_nostroke_radius10.xml
- Aos/app/src/main/res/drawable/rect_primary6_nostroke_30radius.xml
- Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
- Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
- Aos/app/src/main/res/layout/fragment_home.xml
- Aos/app/src/main/res/layout/fragment_restaurant_detail.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search.xml
- Aos/app/src/main/res/layout/item_home_filter.xml
- Aos/app/src/main/res/layout/item_home_search.xml
- Aos/app/src/main/res/navigation/nav_graph.xml
- 테스트 마커 하나 찍기 (서울역 위도경도 기준)
- 마커 클릭했을때 BottomSheet 구현
- 상세화면 임시버튼 → 클릭시 맛집리스트 추가 화면으로 이동
- 홈 화면 필터 리스트 RecyclerView 
- 검색바 눌렀을때 검색화면으로 이동
- 홈화면 세팅 및 분업 준비 완료
- BottomSheet 구현 완료
related to issue #63
related to issue #66
related to issue #68
> [Pair/aos] 홈 화면이동 구성, BottomSheet 구현

- be/package-lock.json
- be/package.json
- be/src/restaurant/entities/restaurant.entity.ts
- be/src/restaurant/restaurant.controller.ts
- be/src/restaurant/restaurant.repository.ts
- be/src/restaurant/restaurant.service.ts
서울시 공공 api로 음식점 리스트 DB에 저장
https://www.osgeo.kr/17
Related to Iusse : #63
> [Home/be] 서울시 공공 api로 음식점 리스트 DB에 저장

- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/BaseState.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/BaseResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyInfoResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/MyPageApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/ValidationApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/ValidationRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository_impl/MyPageRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileBindingAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit_profile/EditProfileViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashViewModel.kt
- Aos/app/src/main/res/layout/fragment_edit_profile.xml
- Aos/app/src/main/res/layout/fragment_my_restaurant_list.xml
- Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
- Aos/app/src/main/res/navigation/nav_graph.xml
- ApiState 네이밍 변경 -> BaseState
- runNNApi -> runRemote / runLocal 로 BaseState 변환하도록 수정
- BaseResponse 로 모든 데이터 반환 wrapping
- 변경된 사항 적용
- package 네이밍 변경
related to issue #86
> [Pair/aos] data layer 처리 로직 변경 

- be/src/restaurant/dto/seachInfo.dto.ts
- be/src/restaurant/restaurant.controller.ts
- be/src/restaurant/restaurant.repository.ts
- be/src/restaurant/restaurant.service.ts
> [Home/be] 음식점 검색 시 현위치 기반 거리 순 정렬 조회

- be/src/restaurant/entities/restaurant.entity.ts
- be/src/review/entities/review.entity.ts
- be/src/user/entities/user.entity.ts
- be/src/user/entities/user.followList.entity.ts
- be/src/user/entities/user.restaurantlist.entity.ts
엔티티 참조 관계 수정
Related to issue : #33
> [Home/be] 엔티티 참조 관계 수정

- be/src/restaurant/dto/seachInfo.dto.ts
- be/src/restaurant/restaurant.service.ts
- be/src/user/user.controller.ts
- be/src/user/user.followList.repository.ts
- be/src/user/user.module.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
[Home/be] 홈 화면 내 맛집 필터 + 위치기반 거리 적용
Related to iusse : #63
> [Home/be] 홈 화면 내 맛집 필터 + 위치기반 거리 적용

- Aos/.idea/deploymentTargetDropDown.xml
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/ApiModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/RepositoryModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/SearchRestaurantResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/adapter/RestaurantSearchAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiSearchResultDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/model/UiRestaurantData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/HideKeyBoard.kt
- Aos/app/src/main/res/drawable/rect_dark7fill_nostroke_10radius.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search.xml
[음식점 검색 구현](https://github.com/boostcampwm2023/and06-nibobnebob/pull/116)
> 홈 음식점 검색 구현

- be/src/user/user.controller.ts
- be/src/user/user.followList.repository.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
팔로잉 탭 기능 구현
Related to issue : #57, #71, #72, #73
> [Follow/be] 팔로우/팔로잉 리스트, 팔로우/언팔로우, 유저 자동완성 검색, 다른 유저 메인페이지 정보

- be/src/review/dto/reviewInfo.dto.ts
- be/src/review/review.module.ts
- be/src/review/review.repository.ts
- be/src/user/user.controller.ts
- be/src/user/user.module.ts
- be/src/user/user.service.ts
맛집 등록 api 응답 구현
Related to issue : #69
> [맛집등록하기/be] 맛집 등록 api 응답 구현

- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> 마이페이지 로그아웃

- be/src/review/dto/reviewInfo.dto.ts
- be/src/review/entities/review.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
등록, 삭제, 재등록
Related to iusse : #31, #69
> [맛집리스트 등록/be] 등록, 삭제, 재등록

- be/src/review/dto/reviewInfo.dto.ts
- be/src/review/entities/review.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
> 맛집 리스트 재등록, 삭제

- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> [팔로우/be] 다른 사용자 추천, 팔로우/팔로잉 응답 수정

- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> 다른 사용자 추천, 팔로우/팔로잉 응답 수정

- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> [Follow/be]  팔로우/팔로워/추천 사용자 리스트 응답 구조 수정

- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> 팔로우/팔로워/추천 사용자 리스트 응답 구조 수정

- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/DataExtensions.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyPageInfoDataMapper.kt
- 로그아웃 api 연결
- 생년월일 -> 연령대 표시
- 로그아웃 api 연결
- 마이페이지 연령대 표시
- strings.xml 로 관리하고 싶은데 그러려면 bindingAdapter 에서 확장함수로 정의해야함.. 이건 내일 설명할게!
- 혹시 회원탈퇴처럼 서버에서 아직 처리 안됐을까봐 로그아웃 api 테스트는 아직 안함! 내일 낮에 하겠습니다~\
related to issue #18 
related to issue #22
> [MyPage/aos] 로그아웃 api 연결 및 연령대 표시

- be/src/restaurant/restaurant.controller.ts
- be/src/restaurant/restaurant.module.ts
- be/src/restaurant/restaurant.repository.ts
- be/src/restaurant/restaurant.service.ts
- 음식점 정보 응답시 리뷰 테이블을 join하여 리뷰 개수 확인 및 응답
- 필터링된 음식점 쿼리 수정 및 구조 변경
- 음식점 상세정보 응답 변경
- 전체 음식점 리스트 반환 api 구현
Related to Issue #63,#66, #104
> [Home/be] 음식점 정보 응답 시 리뷰를 반영하여 응답

- be/src/restaurant/restaurant.repository.ts
- be/src/user/entities/user.wishrestaurantlist.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.module.ts
- be/src/user/user.service.ts
- be/src/user/user.wishrestaurantList.repository.ts
위시리스트 등록/삭제/가져오기 구현
Related to issue : #32
> [WishList/be] 위시리스트 등록/삭제/가져오기 구현

- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
다른 유저 메인 페이지 정보 요청 api 응답 구조 수정
> [Follow/be] 다른 유저 메인 페이지 정보 요청 api 응답 구조 수정

- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
> 다른 유저 메인 페이지 정보 요청 api 응답 속성 추가

- be/src/restaurant/restaurant.repository.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
- 위시 맛집 리스트 등록 여부 응답
- 내 맛집 리스트 응답 수정
Related to Issue #31 #63 #66
> [Home/be] 위시 맛집리스트 등록 여부 응답 및 내 맛집 리스트 응답 수정

- be/src/auth/auth.controller.ts
- be/src/main.ts
- be/src/restaurant/dto/filterInfo.dto.ts
- be/src/restaurant/dto/location.dto.ts
- be/src/restaurant/dto/seachInfo.dto.ts
- be/src/restaurant/entities/restaurant.entity.ts
- be/src/restaurant/restaurant.controller.ts
- be/src/restaurant/restaurant.repository.ts
- be/src/restaurant/restaurant.service.ts
- be/src/review/entities/review.entity.ts
- be/src/review/review.module.ts
- be/src/review/review.repository.ts
- be/src/user/entities/user.entity.ts
- be/src/user/entities/user.restaurantlist.entity.ts
- be/src/user/entities/user.wishrestaurantlist.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.followList.repository.ts
- be/src/user/user.module.ts
- be/src/user/user.repository.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
- be/src/user/user.wishrestaurantList.repository.ts
- prettier 적용
- swagger api 문서 수정
Related to Issue #35
> [Global/be] prettier 적용 및 api tag 적용

- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
> 다른 유저 메인 마이페이지 에러 및 응답 수정

- be/src/restaurant/restaurant.repository.ts
- be/src/user/user.controller.ts
- be/src/user/user.service.ts
- be/src/utils/parsearraypipe.ts
api 응답 fix
Relate to iusse : #57, #69
> [Global/be] api 응답 fix, 유저 검색 필터 중첩 적용

- be/docker-compose.yml
- be/package.json
- be/src/restaurant/restaurant.service.ts
- be/src/user/entities/user.restaurantlist.entity.ts
- be/src/user/entities/user.wishrestaurantlist.entity.ts
- be/src/user/user.service.spec.ts
> 마이페이지 테스트 코드 작성

- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/NavigationExtensions.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
- Aos/app/src/main/res/layout/fragment_home.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search_map.xml
- Aos/app/src/main/res/navigation/nav_graph.xml
- 검색 후 새로운 fragment 에서 결과 지도 찍기
- 다시 검색창으로 돌아올 경우 검색어 유지
- 화면간 이동 구현
- (추가) 홈화면 상단 검색바 디자인 통일
- 해당 위치로 이동시, BottomSheet가 올라와, 상세정보를 표시해준다
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/b48c4526-e4d0-43d8-aae0-1bf741ab1c9c
related to issue #66
> [Home/aos] 검색 기능 마무리

- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyWishListDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyListData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyWishData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/MyWishListViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
- Aos/app/src/main/res/layout/fragment_wish_restaurant_list.xml
- Aos/app/src/main/res/layout/item_my_list.xml
- Aos/app/src/main/res/layout/item_wish_list.xml
- Aos/app/src/main/res/menu/my_page_wish_list_menu.xml
- Aos/app/src/main/res/values/strings.xml
- 위시 맛집 리스트 api 연결
- 위시 맛집 리스트 삭제, 상세보기, 맛집리스트에 추가 구현
- 위시 맛집 리스트 & 맛집 리스트 삭제 시 dialog 구현
- 위시 맛집 아이템을 클릭하였을 때 맛집 상세화면 보기로 이동한다.
- 삭제버튼 클릭 시 위시 맛집 목록이 변경된다.
- 맛집추가 버튼 클릭 시 맛집 추가하기 화면으로 이동한다.
- 맛집 리스트에 추가
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/09ef22f1-5628-4e32-9d61-a838692504f1
- 위시 리스트에서 삭제
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/c98c5bf7-ac0b-4554-8a21-2f26e2045bb4
related to issue #32
> [MyPage/aos] 위시 맛집 리스트 구현

- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
[홈 필터 클릭시 이동 알고리즘 적용](https://github.com/boostcampwm2023/and06-nibobnebob/pull/174)
> 홈 필터 클릭 시 이동 알고리즘 적용

- be/src/user/user.controller.ts
- be/src/user/user.service.ts
위시 맛집 포함 여부 정보 요청 api 응답 구현
Related to issue : #104
> [WishList/be] 위시 맛집 포함 여부 정보 요청 api 응답 구현

- be/src/user/user.controller.ts
- be/src/user/user.service.ts
> 위시 맛집 포함 여부 요청 api 구현

- Aos/app/src/main/java/com/avengers/nibobnebob/app/NetworkManager.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/base/BaseFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/IntroActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/MainActivity.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/FollowFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/follow/search/FollowSearchViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantdetail/RestaurantDetailFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/MyPageFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/edit/EditProfileFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mylist/MyRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/splash/SplashActivity.kt
- 통일되지 않은 액티비티, 프래그먼트의 initView, initEventObserver 템플릿 메서드 적용
- 통일되지 않은 네이밍 통일
- 네트워크에 연결에 대한 대응  
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/e6f2da9b-f2f7-4738-aaba-262d345abfbc
- 하는김에 네트워크연결에 데한 여부 판단에 통신을 진행해 보았는데 해도 괜찮은지?
> [Global/aos] init 템플릿 메소드 패턴 적옹 및 네트워크 간단한 대응

- Aos/app/src/main/java/com/avengers/nibobnebob/config/BearerInterceptor.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/request/BasicLoginRequest.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/LoginResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/IntroApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RefreshApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/IntroRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/model/UiLoginData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/DetailSignupViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/SignupUiState.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/ValidationUtil.kt
- Aos/app/src/main/res/layout/fragment_basic_signup.xml
- Aos/app/src/main/res/layout/fragment_login.xml
- Aos/app/src/main/res/navigation/intro_nav_graph.xml
https://github.com/boostcampwm2023/and06-nibobnebob/assets/86242930/d5b54c10-529d-4978-b7c5-bafc5dad178d
https://github.com/boostcampwm2023/and06-nibobnebob/assets/86242930/3b8404f1-abde-4724-8c76-350399897b3b
Related to Issue: #15 #5
> [Login-Final/aos] 일반로그인 / 회원가입 구현

- Aos/app/src/main/java/com/avengers/nibobnebob/app/di/NetworkModule.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/HomeApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/HomeRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/NavigationExtensions.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/ImageButtonBindingAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/restaurantadd/AddMyRestaurantFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/mapper/UiRestaurantDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
- Aos/app/src/main/res/layout/fragment_home.xml
- Aos/app/src/main/res/navigation/nav_graph.xml
주요작업과 동일 
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/f3ead567-aa7e-4753-a0c0-4f03b7409ee5
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/227a99fa-11cb-4cc4-965f-07ac183a6ef6
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/e03aa7eb-245d-4a94-9dd9-b91f3c4cec26
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/fcd7b919-9119-4aba-92b9-2bcbabaeb3e8
- 근처 음식점 찾기에 대해서 어떻게 생각하는지? (전체 음식점을 다 받는것이 과연 맞는것인지)
related to Issue #62 #68 #69
> [home/aos] 맛집 추가 후 로직, 메인화면 보완 

- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/RestaurantIsWishResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/search/RestaurantSearchMapViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
- wish list check api 연동
- wish list 상태를 search - bottom sheet 에서 변경하였을 경우 바로 업데이트 구현
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/713feee6-6fa3-40e4-865d-9695e6d68403
- wish 포함 여부 체크하는 api 는 화면 넘어갈때만 적용시키고, search map 안에서 변경되는 state 는 그냥 변수로 관리함! (화면 전환되면 최신 데이터 받아오기 때문에 문제 없다고 판단)
> [Home/aos] 검색 후 지도에서 위시리스트 여부 업데이트

- be/src/user/user.controller.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
- be/src/user/user.wishrestaurantList.repository.ts
- be/src/utils/sortInfo.dto.ts
> 맛집, 위시 맛집 정렬 및 페이징 기능 구현

- .github/workflows/be-autodeploy.yml
- be/src/user/user.controller.ts
> 음식점 추천 기능 구현

- be/src/review/dto/reviewInfo.dto.ts
- be/src/user/entities/user.entity.ts
- be/src/user/entities/user.restaurantlist.entity.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
- 추천 유저 알고리즘 구현
Related to Issue #70
> [Follow-Final/be] 추천 유저 알고리즘 구현

- be/src/auth/auth.service.ts
- be/src/user/user.controller.ts
- be/src/user/user.repository.ts
- be/src/user/user.service.ts
> [Global-Final/be] 회원가입 시 홈화면 진입을 위한 토큰값 반환

- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/util/Constants.kt
- Aos/app/src/main/res/layout/fragment_home.xml
- 음식점 정보 클릭시 카메라 위치 찍기
- 기본 음식점 필터 버튼 유무에 따른 플로팅 버튼 visibility조정
- 근처 음식점 임시 radius, zoom 레벨 삭제 후 적용
https://github.com/boostcampwm2023/and06-nibobnebob/assets/76191161/3af50478-df0c-4762-9620-541909ba28a3
- 메뉴 추천 부분이 서버에서 internal error가 뜨고 마침 서버도 또 터져서.. 이부분만 먼저 merge하고 내일 이어서 작업할게!
> [Home/aos] 홈화면 필터, 주변 맛집 마커 보완

- be/src/restaurant/restaurant.service.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
음식점 추천 에러 fix, 음식점 상세 응답에 데이터 추가
Related to issue : #64
> [Global-Final/be] 음식점 추천 에러 fix, 음식점 상세 응답에 데이터 추가

- be/src/restaurant/restaurant.service.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
> 맛집 상세 페이지 리뷰 응답 데이터 추가, 음식 추천 에러 fix

- be/package-lock.json
- be/package.json
- be/src/restaurant/restaurant.module.ts
- be/src/restaurant/restaurant.service.ts
Cron 스케줄러 적용
Related to issue : #35
> [Global-Final/be] Cron 스케줄러 적용

- be/package-lock.json
- be/package.json
- be/src/restaurant/restaurant.module.ts
- be/src/restaurant/restaurant.service.ts
> cron을 적용하여 DB 업데이트

- be/src/restaurant/restaurant.service.ts
- be/src/review/review.service.ts
- be/src/user/user.service.ts
팔로우 / 팔로워 리스트 응답 사진, 리뷰 이미지 응답 수정
> [Global/be] 팔로우 / 팔로워 리스트 응답 사진, 리뷰 이미지 응답 수정

- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/MyPageRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/login/LoginViewModel.kt
- Aos/app/src/main/res/layout/fragment_login.xml
- 일반 로그인 시 체크박스 여부 확인하여 자동 로그인 값 저장
- 로그아웃 시 자동로그인 저장값 삭제
- 자동로그인 설정 x
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/e134e93b-0d89-42ba-8987-7ad8216b04dd
- 자동로그인 설정 o
https://github.com/boostcampwm2023/and06-nibobnebob/assets/82799840/5146b694-5799-4838-9ac7-656cc0b6a130
related to issue #22
> [Login,Logout/aos]자동로그인 관리

- be/package-lock.json
- be/package.json
- be/src/aws/aws.service.ts
- be/src/main.ts
Object Storage 저장 이미지 리사이징
Related to Issue : #35
> [Global-Final/be] Object Storage 저장 이미지 리사이징

- be/package-lock.json
- be/package.json
- be/src/aws/aws.service.ts
- be/src/main.ts
> Object Storage 저장 이미지 리사이징

- be/src/auth/auth.service.ts
- be/src/aws/aws.service.ts
- be/src/restaurant/entities/restaurant.entity.ts
- be/src/restaurant/restaurant.controller.ts
- be/src/restaurant/restaurant.module.ts
- be/src/restaurant/restaurant.repository.ts
- be/src/restaurant/restaurant.service.ts
- be/src/review/entities/review.entity.ts
- be/src/review/entities/review.like.entity.ts
- be/src/review/review.controller.ts
- be/src/review/review.like.repository.ts
- be/src/review/review.repository.ts
- be/src/review/review.service.ts
- be/src/user/entities/user.entity.ts
- be/src/user/user.controller.ts
- be/src/user/user.restaurantList.repository.ts
- be/src/user/user.service.ts
- be/test/app.e2e-spec.ts
로그인 실패 응답 구조 변경
- 401 Unauthorized Error -> 403 Forbidden Error
상대 경로로 수정
- 절대 경로를 모두 상대 경로로 수정
> 로그인 실패 응답 구조 변경, 상대 경로로 수정

- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/RestaurantRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/bindingadapters/TextViewBindingAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/intro/signup/BasicSignupViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/mapper/UiUserDetailDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/model/UiUserDetailData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/UserDetailViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/global/userdetail/adapter/UserDetailRestaurantAdapter.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeFragment.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/wishlist/WishRestaurantListFragment.kt
- Aos/app/src/main/res/layout/bottom_sheet_restaurant.xml
- Aos/app/src/main/res/layout/fragment_add_my_restaurant.xml
- Aos/app/src/main/res/layout/fragment_basic_signup.xml
- Aos/app/src/main/res/layout/fragment_follow.xml
- Aos/app/src/main/res/layout/fragment_login.xml
- Aos/app/src/main/res/navigation/nav_graph.xml
- Aos/app/src/main/res/values/strings.xml
- 마커 로딩시 로딩 다이엉로그 추가 및 음식점 갯수 제한
- 근처 음식점 마커 갯수 설정
- 리뷰 추가 접근성 반대 오류 수정
- 바텀 시트 버튼 잘림 현상 수정
- 팔로워 맛집 클릭시 음식점 상세보기 이동
- 팔로우 프래그먼트 중첩 스크롤 (빈 여백) 삭제
- 기본회원가입 "중복확인" 버튼과 이메일 비어있을 때 비어있음을 표시
- 위시맛집 화면 전환 네비게이션 수정
- 네이버 로그인 텍스트 가운데 정렬
> [hotfix/aos] Hotfix

- Aos/app/src/main/java/com/avengers/nibobnebob/data/model/response/MyRestaurantResponse.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/remote/RestaurantApi.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/data/repository/RestaurantRepositoryImpl.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/domain/model/MyRestaurantData.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/domain/repository/RestaurantRepository.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/domain/usecase/restaurant/GetMyRestaurantListUseCase.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/home/HomeViewModel.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/mapper/UiMyListDataMapper.kt
- Aos/app/src/main/java/com/avengers/nibobnebob/presentation/ui/main/mypage/model/UiMyListData.kt
- Aos/app/src/main/res/layout/fragment_basic_signup.xml
- Aos/app/src/main/res/layout/fragment_home.xml
- Aos/app/src/main/res/layout/fragment_login.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search.xml
- Aos/app/src/main/res/layout/fragment_restaurant_search_map.xml
- 홈화면 검색바의 hint 메시지 padding, text size 줄이기
- email 입력하는 input 창에 email type 지정
> [Hotfix/aos]Hotfix 

- be/package-lock.json
- be/package.json
- be/src/main.ts
- be/src/restaurant/elasticSearch.service.ts
- be/src/restaurant/restaurant.module.ts
- be/src/restaurant/restaurant.service.ts
- 기존에 자체 DB 내에서 진행되던 음식점 이름 검색 및 자동완성을 Elastic search를 활용하여 시간 개선
|10번 동시 요청 |하나씩 차례로 10번 요청 |
|:---:|:---:|
| 평균 156ms | 평균 109ms |
|10번 동시 요청 |하나씩 차례로 10번 요청 |
|:---:|:---:|
| 평균 59ms | 평균 46ms |
> [Home] Elastic search를 활용하여 음식점 자동완성 개선
